export const CLEAR_STATE = 'CLEAR_STATE';
export const SET_ACTIVE_TASK = 'SET_ACTIVE_TASK'; 
export const SET_USER = 'SET_USER'; 
export const CANCEL_TASK = 'CANCEL_TASK'; 
export const SET_ACTIVE_GROUP = 'SET_ACTIVE_GROUP'; 

export const BEGIN_ASYNC_REQUEST = 'BEGIN_ASYNC_REQUEST';
export const ASYNC_REQUEST_COMPLETED = 'ASYNC_REQUEST_COMPLETED';
export const ASYNC_REQUEST_ERROR = 'ASYNC_REQUEST_ERROR';

