export const CLEAR_STATE = "CLEAR_STATE";

export const SET_USER = "SET_USER";

export const SET_TASK_CONTEXT_ID = "SET_TASK_CONTEXT_ID";
export const SET_TASK_CONTEXT_INSTANCE = "SET_TASK_CONTEXT_INSTANCE";
export const SET_ACTIVE_TASK_TAB = "SET_ACTIVE_TASK_TAB";

export const OPEN_TASK = "OPEN_TASK";
export const OPEN_TASK_WITH_INSTANCE_ID = "OPEN_TASK_WITH_INSTANCE_ID";
export const CLOSE_TASK = "CLOSE_TASK";

export const SET_CLASS_MODELS = "SET_CLASS_MODELS";
