export const CLEAR_STATE = "CLEAR_STATE";
export const SET_USER = "SET_USER";
export const SET_ACTIVE_GROUP = "SET_ACTIVE_GROUP";

export const BEGIN_ASYNC_REQUEST = "BEGIN_ASYNC_REQUEST";
export const ASYNC_REQUEST_COMPLETED = "ASYNC_REQUEST_COMPLETED";
export const ASYNC_REQUEST_ERROR = "ASYNC_REQUEST_ERROR";

export const SET_TASK_CONTEXT_ID = "SET_TASK_CONTEXT_ID";
export const SET_TASK_CONTEXT_INSTANCE = "SET_TASK_CONTEXT_INSTANCE";
export const SET_ACTIVE_TASK = "SET_ACTIVE_TASK";
export const CANCEL_TASK = "CANCEL_TASK"; // DO NOT USE - to be deprecated
export const OPEN_TASK = "OPEN_TASK";
export const CLOSE_TASK = "CLOSE_TASK";

export const SET_SIDEBAR_CONTEXT = "SET_SIDEBAR_CONTEXT";
